### ISSUE TITLE
更新订阅出错

### ISSUE THREAD

**Issue by musva** [TkYu/V2RayShell#1]
更新订阅出错，重新启动客户端仍旧报错。
删除配置文件后能正常启动。
![SharedScreenshot](https://user-images.githubusercontent.com/15194803/96554995-d418b100-12e9-11eb-85d2-7003bc77072b.jpg)

**Comment by TkYu** [comment]
看这样子应该是解码base64失败了，订阅的地址能直接访问么？

**Comment by musva** [comment]
我测试了两个地址 有个能正常访问,一个不能,也勾选了使用代理均会报错.

**Comment by TkYu** [comment]
先看看是网络原因还是内容原因吧，目前只支持类ss-win的那种订阅格式（把vmess://的地址按换行符分隔，然后使用base64编码一次再去掉末尾的=号得到），其他的比如clash或者surge之类的专用订阅格式还没去适配，当然也不排除有些平台使用了他们自己发明的新格式。

你可以先诊断下出错的那个订阅，比如直接全局代理拿浏览器隐身模式去访问，能得到内容就不是网络问题，然后再看看得到的内容，如果是base64编码的就debase64一下然后看看原文是啥样，如果是可解析的内容格式但是程序没适配上的话，之后更新可以加上适配

**Comment by musva** [comment]
vmess订阅， 浏览器可抓到内容，其他软件（v2rayN）能正常获取订阅。
